version: 2
jobs:
  checkout_and_install:
    docker:
      - image: circleci/node:11
    working_directory: ~/balancer
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --quiet
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: balancer-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/balancer
  lint:
    docker:
      - image: circleci/node:11
    working_directory: ~/balancer
    steps:
      - restore_cache:
          key: balancer-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint contracts
          command: yarn lint:contracts
      - run:
          name: Lint tests
          command: yarn lint
  build:
    docker:
      - image: circleci/node:11
      - image: ethereum/solc:0.5.11
    working_directory: ~/balancer
    steps:
      - restore_cache:
          key: balancer-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Compile contracts
          command: yarn compile
      - save_cache:
          key: balancer-contracts-build-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/balancer
  test:
    docker:
      - image: circleci/node:11
      - image: trufflesuite/ganache-cli
        command: ganache-cli -d -l 4294967295 --allowUnlimitedContractSize
    working_directory: ~/balancer
    steps:
      - restore_cache:
          key: balancer-contracts-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run tests
          command: yarn test
  
  coverage:
    docker:
      - image: circleci/node:11
    working_directory: ~/balancer
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Fetch solc version
          command: docker pull ethereum/solc:0.5.11
      - restore_cache:
          key: balancer-contracts-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Coverage
          command: yarn coverage && cat coverage/lcov.info | ./node_modules/.bin/coveralls

  slither:
    docker:
      - image: trailofbits/eth-security-toolbox
    working_directory: ~/balancer
    steps:
      - checkout
      - run:
          name: Compile
          command: truffle compile
      - run:
          name: Slither
          command: slither . --filter-paths test --exclude=naming-convention,unused-state,solc-version,constable-states,external-function,reentrancy-events

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_and_install
      - lint:
          requires:
            - checkout_and_install
      - build:
          requires:
            - checkout_and_install
      - test:
          requires:
            - build
      - coverage:
          requires:
            - build
      - slither:
          requires:
            - build
      